name: mcumgr_flutter_example
description: Demonstrates how to use the mcumgr_flutter plugin.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  equatable: ^2.0.5
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  archive: ^4.0.7
  flutter_bloc: ^8.1.6
  flutter_blue_plus: ^1.36.6
  http: ^1.5.0
  json_annotation: ^4.9.0
  mcumgr_flutter:
    path: ../
  path_provider: ^2.1.1
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.8.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/
