name: mcumgr_flutter
description: A new flutter plugin project.
version: 0.1.1+1
homepage: "https://docs.flutter.dev/development/tools/sdk/upgrading"

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  protobuf: ^2.1.0
  rxdart: ^0.26.0
  tuple: ^2.0.1

dev_dependencies:
  faker: ^2.1.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: no.nordicsemi.android.mcumgr_flutter
        pluginClass: McumgrFlutterPlugin
      ios:
        pluginClass: McumgrFlutterPlugin

  assets:
    - assets/mock_logs.txt
