name: mcumgr_flutter
description: nRF Connect Device Manager library is a Flutter plugin based on
  Android, iOS and MacOS nRF Connect Device Manager libraries.
version: 0.8.0
homepage: 'https://github.com/NordicSemiconductor/Flutter-nRF-Connect-Device-Manager'

environment:
  sdk: ^3.7.2
  flutter: '>=3.7.2'

dependencies:
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  protobuf: ^6.0.0
  rxdart: ^0.28.0
  tuple: ^2.0.1

dev_dependencies:
  faker: ^2.1.0
  flutter_test:
    sdk: flutter
  pigeon: ^25.3.2

flutter:
  plugin:
    platforms:
      android:
        package: no.nordicsemi.android.mcumgr_flutter
        pluginClass: McumgrFlutterPlugin
      ios:
        pluginClass: McumgrFlutterPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: McumgrFlutterPlugin
        sharedDarwinSource: true

  assets:
    - assets/mock_logs.txt
